/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.espe.UniversityRestaurantCapacitySystem.view;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author Xavier Cordova ESPE-DCCO
 */
public class MainMenu extends javax.swing.JFrame {

   

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {

        

        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        txtNewProduct = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnShowOrders = new javax.swing.JMenuItem();
        mnShowCostumer = new javax.swing.JMenuItem();
        mnQuit = new javax.swing.JMenu();
        mnExitSystem = new javax.swing.JMenuItem();
        mnQuitSesion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuBar1.setForeground(new java.awt.Color(255, 153, 0));
        jMenuBar1.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jMenuBar1ComponentAdded(evt);
            }
        });

        jMenu1.setText("New");

        jMenuItem1.setText("New Costumer");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Add New Order");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        txtNewProduct.setText("Add New Product");
        txtNewProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNewProductActionPerformed(evt);
            }
        });
        jMenu1.add(txtNewProduct);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("View");

        mnShowOrders.setText("Show Orders");
        mnShowOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnShowOrdersActionPerformed(evt);
            }
        });
        jMenu2.add(mnShowOrders);

        mnShowCostumer.setText("Show Costumers");
        mnShowCostumer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnShowCostumerActionPerformed(evt);
            }
        });
        jMenu2.add(mnShowCostumer);

        jMenuBar1.add(jMenu2);

        mnQuit.setText("Exit");

        mnExitSystem.setText("Log out");
        mnExitSystem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnExitSystemActionPerformed(evt);
            }
        });
        mnQuit.add(mnExitSystem);

        mnQuitSesion.setText("Quit Program");
        mnQuitSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnQuitSesionActionPerformed(evt);
            }
        });
        mnQuit.add(mnQuitSesion);

        jMenuBar1.add(mnQuit);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 276, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

        NewCostumer c = new NewCostumer();

        c.setVisible(true);

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed

        NewOrders c = new NewOrders();

        c.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void txtNewProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNewProductActionPerformed
        NewProduct p = new NewProduct();
        p.setVisible(true);
    }//GEN-LAST:event_txtNewProductActionPerformed

    private void mnShowOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnShowOrdersActionPerformed
        NewCostumer c = new NewCostumer();
        c.setVisible(true);


    }//GEN-LAST:event_mnShowOrdersActionPerformed

    private void mnShowCostumerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnShowCostumerActionPerformed
        ShowCostumersTable s = new ShowCostumersTable();
        s.setVisible(true);
    }//GEN-LAST:event_mnShowCostumerActionPerformed

    private void jMenuBar1ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jMenuBar1ComponentAdded


    }//GEN-LAST:event_jMenuBar1ComponentAdded

    private void mnExitSystemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnExitSystemActionPerformed

        LogIn l = new LogIn();

        l.setVisible(true);
    }//GEN-LAST:event_mnExitSystemActionPerformed

    private void mnQuitSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnQuitSesionActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnQuitSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem mnExitSystem;
    private javax.swing.JMenu mnQuit;
    private javax.swing.JMenuItem mnQuitSesion;
    private javax.swing.JMenuItem mnShowCostumer;
    private javax.swing.JMenuItem mnShowOrders;
    private javax.swing.JMenuItem txtNewProduct;
    // End of variables declaration//GEN-END:variables

   
}
